name: 'Get cached dependencies'
description: 'Here we are creating a composite action which will have cached deps'
runs:
  using: composite
  steps:
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        shell: bash